version: '3.8'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    image: node:18
    working_dir: /app
    command: >
      sh -c "corepack enable && corepack prepare yarn@4.0.0 --activate && \
      yarn install && yarn workspace server start:dev"
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - '3000:3000'

  client:
    image: node:18
    working_dir: /app
    command: >
      sh -c "corepack enable && corepack prepare yarn@4.0.0 --activate && \
      yarn install && yarn workspace client dev --host"
    volumes:
      - .:/app
    depends_on:
      - server
    ports:
      - '5173:5173'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html:ro
    depends_on:
      - client
    ports:
      - '80:80'

volumes:
  mysql-data:
