version: '3.8'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    build: ./server
    command: yarn start:dev
    volumes:
      - ./server:/app
    depends_on:
      - mysql
    ports:
      - '3000:3000'

  client:
    build: ./client
    command: yarn dev --host
    volumes:
      - ./client:/app
    depends_on:
      - server
    ports:
      - '5173:5173'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html:ro
    depends_on:
      - client
    ports:
      - '80:80'

volumes:
  mysql-data:
